# Generated by Django 2.2.2 on 2019-06-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
