# Generated by Django 2.2.2 on 2019-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0002_auto_20190610_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
