# Generated by Django 2.2.2 on 2019-06-10 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0003_auto_20190610_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierate',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
