# Generated by Django 2.2.2 on 2019-06-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0004_auto_20190610_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
