# Generated by Django 2.2.2 on 2019-06-11 22:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdb', '0005_movie_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movierate',
            options={'permissions': (('can_vote_two_times', 'Can vote two times'),)},
        ),
        migrations.AlterUniqueTogether(
            name='movierate',
            unique_together={('user', 'movie')},
        ),
    ]
